version: '3'

services:
  postgres:
    image: 'pgvector/pgvector:pg16'
    restart: always
    env_file:
      - .docker.env
    ports:
      - '5432:5432'
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_DB=${POSTGRES_DATABASE:-chatwoot}'
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U ${POSTGRES_USERNAME} -d ${POSTGRES_DATABASE:-chatwoot} -h 127.0.0.1'
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - chatwoot_network

  redis:
    image: 'redis:alpine'
    restart: always
    env_file:
      - .docker.env
    ports:
      - '6379:6379'
    command:
      - redis-server
    volumes:
      - 'redis-data:/data'
    healthcheck:
      test:
        - CMD
        - redis-cli
        - PING
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - chatwoot_network

volumes:
  postgres-data:
  redis-data:

networks:
  chatwoot_network:
    name: chatwoot_network
    external: true
